### ISSUE TITLE
paddle.static.CompiledProgram测评

### ISSUE THREAD

**Issue by sshimii** [PaddlePaddle/docs#4492]
### 文档中英文链接

中文文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/CompiledProgram_cn.html
英文文档：
https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/CompiledProgram_en.html

### 红线问题

英文文档：
方法-代码示例上面缺少note，中英文不一致

### 格式问题

英文文档导航栏不存在，包含Api_attr属性

### 主观评价

英文文档导航栏不存在，包含Api_attr属性，中英文对照后，英文文档缺少note内容

**Comment by Ligoml** [comment]
note需要增加

**Comment by zyl1223582136** [comment]
### PR types
Others

### PR changes
Docs

### Describe
- 删除英文文档中的“Api_attr”属性
- 在“return”下方添加如下注解
> Note:
1. If you're just doing multi-card testing, you don't need to set up loss_name as well as share_vars_from.
2. If there is both model training and model testing in the program, the share_vars_from must be set when building the CompiledProgram corresponding to the model test, otherwise the parameters used for model testing and model training are inconsistent.

@paddle-bot
